from .actions import (
    DEFAULT_DANMAKU_MARKER,
    DanmakuMarkerIntent,
    create_danmaku_action,
    split_danmaku_markers,
    stable_action_id,
    validate_danmaku_action,
    visible_danmaku_stream_text,
)
from .adapters import (
    ActionTransport,
    AnalysisProvider,
    ClientSampleExporter,
    ContextHostAdapter,
    KnowledgeProvider,
    KnowledgeSearchProvider,
    PlaybackAdapter,
    PlotRecallAdapter,
    RuntimeStore,
    StructuredModelProvider,
    SubtitleProvider,
)
from .context import build_context_envelope
from .core import WatchCore, WatchCoreError
from .costs import (
    ANALYSIS_MODEL_PURPOSES,
    AnalysisCostSummary,
    merge_analysis_usage,
    summarize_analysis_cost,
)
from .lifecycle import (
    LifecycleError,
    SessionRuntime,
    WorkCoordinator,
    WorkItem,
    WorkStatus,
)
from .models import (
    ActionValidation,
    AudioSelection,
    ClientCapabilities,
    ContextEnvelope,
    DanmakuAction,
    FearMode,
    KnowledgeMode,
    LocalMediaDescriptor,
    LocalPlaybackCapabilities,
    MediaDescriptor,
    PlaybackSnapshot,
    PlotChunk,
    RiskEvent,
    SampleManager,
    SamplePlan,
    SamplePurpose,
    SessionMode,
    SnapshotApplyResult,
    SubtitleSelection,
    VisualContextMode,
    WatchSession,
)
from .recall import Bm25PlotRecall
from .prompts import (
    COMPANION_VISUAL_USER_LABEL,
    PromptBundle,
    build_analysis_prompt,
    build_companion_context_prompt,
    build_knowledge_prompt,
)
from .providers import (
    KnowledgeSearchConfig,
    KnowledgeSearchMode,
    ModelProviderConfig,
    ProviderSettings,
    build_knowledge_search_query,
)
from .provider_response import (
    StructuredProviderResult,
    StructuredResponseError,
    extract_structured_object,
    normalize_provider_usage,
    parse_openai_compatible_response,
)
from .start_gate import StartGateDecision, evaluate_start_gate
from .timeline import (
    MAX_FUTURE_WINDOW_MS,
    TimelineTracker,
    reply_arrival_until_ms,
    scheduled_future_until_ms,
)

__all__ = [
    "ActionTransport",
    "ActionValidation",
    "ANALYSIS_MODEL_PURPOSES",
    "AnalysisProvider",
    "AnalysisCostSummary",
    "AudioSelection",
    "Bm25PlotRecall",
    "ClientCapabilities",
    "ClientSampleExporter",
    "ContextEnvelope",
    "ContextHostAdapter",
    "COMPANION_VISUAL_USER_LABEL",
    "DEFAULT_DANMAKU_MARKER",
    "DanmakuAction",
    "DanmakuMarkerIntent",
    "FearMode",
    "KnowledgeMode",
    "KnowledgeProvider",
    "KnowledgeSearchConfig",
    "KnowledgeSearchMode",
    "KnowledgeSearchProvider",
    "LifecycleError",
    "LocalMediaDescriptor",
    "LocalPlaybackCapabilities",
    "MAX_FUTURE_WINDOW_MS",
    "MediaDescriptor",
    "PlaybackAdapter",
    "PlaybackSnapshot",
    "PlotChunk",
    "PlotRecallAdapter",
    "PromptBundle",
    "ProviderSettings",
    "RiskEvent",
    "RuntimeStore",
    "SampleManager",
    "SamplePlan",
    "SamplePurpose",
    "SessionMode",
    "SessionRuntime",
    "SnapshotApplyResult",
    "StructuredModelProvider",
    "StructuredProviderResult",
    "StructuredResponseError",
    "SubtitleSelection",
    "SubtitleProvider",
    "TimelineTracker",
    "VisualContextMode",
    "WatchCore",
    "WatchCoreError",
    "WatchSession",
    "WorkCoordinator",
    "WorkItem",
    "WorkStatus",
    "build_context_envelope",
    "build_analysis_prompt",
    "build_companion_context_prompt",
    "build_knowledge_prompt",
    "build_knowledge_search_query",
    "create_danmaku_action",
    "evaluate_start_gate",
    "extract_structured_object",
    "merge_analysis_usage",
    "normalize_provider_usage",
    "parse_openai_compatible_response",
    "reply_arrival_until_ms",
    "scheduled_future_until_ms",
    "split_danmaku_markers",
    "stable_action_id",
    "summarize_analysis_cost",
    "validate_danmaku_action",
    "visible_danmaku_stream_text",
    "ModelProviderConfig",
    "StartGateDecision",
]

__version__ = "0.1.0"
